import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

async function run(command: string, cwd = process.cwd()): Promise<string> {
    const { stdout, stderr } = await execAsync(command, { cwd });
    if (stderr && !stdout) {
        throw new Error(stderr.trim());
    }
    return stdout.trim();
}

export async function isGitRepo(cwd = process.cwd()): Promise<boolean> {
    try {
        await run('git rev-parse --git-dir', cwd);
        return true;
    } catch {
        return false;
    }
}

export async function getCurrentBranch(cwd = process.cwd()): Promise<string> {
    return run('git rev-parse --abbrev-ref HEAD', cwd);
}

export async function branchExists(branchName: string, cwd = process.cwd()): Promise<boolean> {
    try {
        await run(`git show-ref --verify --quiet refs/heads/${branchName}`, cwd);
        return true;
    } catch {
        return false;
    }
}

export async function createBranch(branchName: string, cwd = process.cwd()): Promise<void> {
    const exists = await branchExists(branchName, cwd);
    if (exists) {
        await run(`git checkout ${branchName}`, cwd);
    } else {
        await run(`git checkout -b ${branchName}`, cwd);
    }
}

export async function stageFiles(files: string[], cwd = process.cwd()): Promise<void> {
    const quoted = files.map((f) => `"${f}"`).join(' ');
    await run(`git add ${quoted}`, cwd);
}

export async function stageDirectory(dir: string, cwd = process.cwd()): Promise<void> {
    await run(`git add "${dir}"`, cwd);
}

export async function commit(message: string, cwd = process.cwd()): Promise<void> {
    const escaped = message.replace(/"/g, '\\"');
    await run(`git commit -m "${escaped}"`, cwd);
}

export async function hasUncommittedChanges(cwd = process.cwd()): Promise<boolean> {
    const result = await run('git status --porcelain', cwd);
    return result.length > 0;
}

export async function getUnstagedFiles(cwd = process.cwd()): Promise<string[]> {
    const result = await run('git diff --name-only', cwd);
    return result.split('\n').filter(Boolean);
}

export async function getStagedFiles(cwd = process.cwd()): Promise<string[]> {
    const result = await run('git diff --cached --name-only', cwd);
    return result.split('\n').filter(Boolean);
}

export async function getRemoteUrl(cwd = process.cwd()): Promise<string | null> {
    try {
        return await run('git remote get-url origin', cwd);
    } catch {
        return null;
    }
}

export async function pushBranch(
    branchName: string,
    cwd = process.cwd(),
): Promise<void> {
    await run(`git push -u origin ${branchName}`, cwd);
}

export async function checkGhCli(): Promise<boolean> {
    try {
        await execAsync('gh --version');
        return true;
    } catch {
        return false;
    }
}

export async function createPullRequest(
    title: string,
    body: string,
    baseBranch: string,
    cwd = process.cwd(),
): Promise<string> {
    const hasGh = await checkGhCli();
    if (!hasGh) {
        throw new Error(
            'GitHub CLI (gh) is not installed. Install it from https://cli.github.com/ then run `gh auth login`.',
        );
    }

    const escapedTitle = title.replace(/"/g, '\\"');
    const bodyFile = `/tmp/bifrost-pr-body-${Date.now()}.md`;

    const { writeFileSync } = await import('fs');
    writeFileSync(bodyFile, body, 'utf8');

    try {
        const url = await run(
            `gh pr create --title "${escapedTitle}" --body-file "${bodyFile}" --base "${baseBranch}"`,
            cwd,
        );
        return url;
    } finally {
        const { unlinkSync } = await import('fs');
        try {
            unlinkSync(bodyFile);
        } catch {
            // ignore cleanup errors
        }
    }
}

export function buildCommitMessage(
    featureName: string,
    featureDescription: string,
    timeline: Array<{ timestamp: string; message: string }>,
    artifacts: Array<{ agent: string; path: string }>,
): string {
    const timelineText = timeline
        .map((e) => `- ${e.timestamp}: ${e.message}`)
        .join('\n');

    const artifactsText = artifacts
        .map((a) => `- ${a.agent}: ${a.path}`)
        .join('\n');

    return [
        `feat: ${featureName} - generated by Bifrost`,
        ``,
        `## Summary`,
        featureDescription,
        ``,
        `## Timeline`,
        timelineText,
        ``,
        `## Artifacts`,
        artifactsText,
        ``,
        `Bifrost: https://github.com/bifrost-framework`,
        `Generated: ${new Date().toISOString()}`,
    ].join('\n');
}

export async function applyPatch(patchPath: string, cwd = process.cwd()): Promise<void> {
    await run(`git apply "${patchPath}"`, cwd);
}

export function buildPrBody(
    featureName: string,
    featureDescription: string,
    timeline: Array<{ timestamp: string; message: string }>,
    artifacts: Array<{ agent: string; path: string }>,
): string {
    const timelineText = timeline
        .slice(-10)
        .map((e) => `- ${e.timestamp}: ${e.message}`)
        .join('\n');

    const artifactsText = artifacts
        .map((a) => `- ${a.agent}: \`${a.path}\``)
        .join('\n');

    return [
        `## Summary`,
        ``,
        featureDescription,
        ``,
        `## Artifacts`,
        ``,
        artifactsText || '_(none)_',
        ``,
        `## Timeline`,
        ``,
        timelineText || '_(none)_',
        ``,
        `---`,
        `> Generated by [Bifrost](https://github.com/bifrost-framework) — ${new Date().toISOString()}`,
    ].join('\n');
}
