import { Command, Flags } from '@oclif/core';
import * as path from 'path';
import * as fs from 'fs-extra';
import { prompt } from 'enquirer';
import { AgentName, BifrostStatus } from '../types';
import { loadConfig, getBifrostDir, getStatePath } from '../config';
import { readState, updateStatus, addTimeline, validateState } from '../core/state/manager';
import {
    showSplash,
    success,
    fail,
    warn,
    info,
    blank,
    header,
    spinner,
    renderStatus,
    renderNextSteps,
} from '../ui';

export default class Start extends Command {
    static description = 'Prepare the feature workflow for Claude Code execution';

    static examples = [
        '<%= config.bin %> start',
    ];

    static flags = {
        path: Flags.string({
            char: 'p',
            description: 'Project path (defaults to current directory)',
            default: process.cwd(),
        }),
    };

    async run(): Promise<void> {
        const { flags } = await this.parse(Start);
        const projectPath = path.resolve(flags['path']);
        const config = loadConfig(projectPath);

        const bifrostDir = getBifrostDir(projectPath);
        const statePath = getStatePath(projectPath);

        header('bifrost start');
        blank();

        if (!(await fs.pathExists(statePath))) {
            this.error('Nenhum .bifrost/ encontrado. Execute `bifrost init` primeiro.');
        }

        const loadSpinner = spinner('Loading project state...').start();
        let state;
        try {
            state = await readState(statePath);
            loadSpinner.succeed('State loaded');
        } catch (err) {
            loadSpinner.fail('Falha ao ler STATE.md');
            this.error(err instanceof Error ? err.message : String(err));
        }

        const stateValidation = validateState(state);
        if (!stateValidation.success) {
            fail('STATE.md é inválido:');
            for (const e of stateValidation.errors) {
                info(`  - ${e}`);
            }
            this.error('Corrija o STATE.md antes de iniciar.');
        }

        if (state.status !== BifrostStatus.INITIALIZED) {
            const { proceed } = await prompt<{ proceed: string }>({
                type: 'select',
                name: 'proceed',
                message: `Status atual é "${state.status}". Deseja reiniciar o fluxo?`,
                choices: ['Sim — resetar e reiniciar fluxo', 'Não — abortar'],
            });
            if (!proceed.startsWith('Sim')) {
                info('Cancelado.');
                return;
            }
        }

        if (state.blockers.length > 0) {
            warn('Existem bloqueios abertos:');
            state.blockers.forEach((b) => warn(`  - ${b}`));
            
            if (!flags.force) {
                info('Resolva os bloqueios no STATE.md, e execute novamente `bifrost start`.');
                return;
            }
            warn('Forçando início apesar dos bloqueios...');
        }

        blank();

        info(`Preparando ${AgentName.INTAKE}...`);
        blank();

        await updateStatus(statePath, BifrostStatus.INTAKE);
        await addTimeline(statePath, `Workflow prepared for ${AgentName.INTAKE}`);

        const finalState = await readState(statePath);
        blank();
        renderStatus(finalState);

        renderNextSteps([
            'Open Claude Code and run `/bifrost:start` to execute native skills',
            'Review .bifrost/IMPACT.md (generated by @Intake)',
            'Run `bifrost status` to see current state',
        ]);
    }
}

